### ISSUE TITLE
Transaction details

### ISSUE THREAD

**Issue by andrew-chang-dewitt** [andrew-chang-dewitt/hoops-client#7]
- [ ] When a User navigates to a list of Transactions they are shown a list of Transactions
- [ ] When a User clicks on an Transaction in the list, they are taken to `/<some-transaction-list-path>/:transaction-id`
- [ ] When a User navigates to `/<some-transaction-list-path>/:transaction-id`, they are shown the details of that Transaction and an edit button
- [ ] When a User clicks on the Transaction details edit button, they are taken to `/<some-transaction-list-path>/:transaction-id/edit`
- [ ] When a User navigates to `/<some-transaction-list-path>/:transaction-id/edit` they are shown a form for editing the Transaction details
- [ ] When a User fills out & submits the Transaction details edit form, they are taken back to `/<some-transaction-list-path>/:transaction-id` and the updated details appear
