### ISSUE TITLE
Hoop details

### ISSUE THREAD

**Issue by andrew-chang-dewitt** [andrew-chang-dewitt/hoops-client#8]
- [ ] When a User navigates to `/hoops` they are shown a list of Hoops
- [ ] When a User clicks on a Hoop in the list, they are taken to `/hoops/:hoop-id`
- [ ] When a User navigates to `/hoops/:hoop-id`, they are shown the details of that Hoop and an edit button
- [ ] When a User clicks on the Hoop details edit button, they are taken to `/hoops/:hoop-id/edit`
- [ ] When a User navigates to `/hoops/:hoop-id/edit` they are shown a form for editing the Hoop details
- [ ] When a User fills out & submits the Hoop details edit form, they are taken back to `/hoops/:hoop-id` and the updated details appear
